### ISSUE TITLE
Outputs changes for Suntwins 4000TL

### ISSUE THREAD

**Issue by srrsparky** [ridale/solarmon#2]
No so much of an issue, but may assist others.

I have a Suntwins 4000TL with two strings of arrays. I think I have sorted out the different outputs, but not 100% with the string DC currents. These are the outputs I have changed in solarmon.c

    int16_t Temp    = ((buf[0] << 8)  + buf[1]); // 10.0;
    uint16_t VDC1    = ((buf[2] << 8) + buf[3]);
    uint16_t VDC2   = ((buf[4] << 8)  + buf[5]); // 10.0;
    uint16_t IDC1   = ((buf[6] << 8) + buf[7]);
    uint16_t IDC2   = ((buf[8] << 8) + buf[9]);
    uint16_t TodayE = ((buf[10] << 8)  + buf[11]); // 100.0;
    uint16_t IAC    = ((buf[12] << 8)  + buf[13]); // 10.0;
    uint16_t VAC    = ((buf[14] << 8)  + buf[15]); // 10.0;
    uint16_t FAC    = ((buf[16] << 8) + buf[17]); // 100.0;
    int16_t CurrP   = ((buf[18] << 8) + buf[19]);
    char str[512];
    memset(str,0, 512);
    snprintf(str, 512, "{\"Temp\":%d,\"VDC1\":%u,\"VDC2\":%u,\"IDC1\":%u,\"IDC2\":%u,\"TodayE\":%u,\"IAC\":%u,\"VAC\":%u,\"FAC\":%u,\"CurrP\":%d}",
        Temp, VDC1, VDC2, IDC1, IDC2, TodayE, IAC, VAC, FAC, CurrP );

**Comment by ridale** [comment]
Thanks for that, when I get a chance I'll include these with a command line switch  (--twins or similar).

If you can dump some of the output strings and attach them in a comment I can have a check on the DC currents if you'd like.

**Comment by ridale** [comment]
Added the suntwin parsing and command line switch. Cannot test, no access to inverter
